---
- hosts: jenkins
  become: true
  vars_files:
    - group_vars/variables.yml
  roles:
    - { role: debian_base }
    - { role: java }
    - { role: tomcat }
    - { role: docker }
    - { role: maven }
    - { role: jenkins }
