[jenkins]
198.199.72.58 ansible_user=adrian ansible_become_password=adrian

#[dev]
#174.138.44.23 ansible_user=adrian ansible_password=adrian  ansible_become_password=adrian

[dev]
174.138.44.23 ansible_ssh_user=adrian ansible_ssh_pass=adrian ansible_become_password=adrian

[dev:vars]
ipJenkins=198.199.72.58
